{% set name = "exercism" %}
{% set version = "3.0.7" %}

package:
  name: exercism
  version: {{ version }}

source:
  url: https://github.com/exercism/cli/releases/download/v{{ version }}/exercism-linux-64bit.tgz  # [linux64]
  sha256: d4a19aa4935059fcec1bd1a11ae4c2942b254ba0209125105aa2918e4cc2e59f  # [linux64]
  url: https://github.com/exercism/cli/releases/download/v{{ version }}/exercism-linux-32bit.tgz  # [linux32]
  sha256: 74bbdab4c77e8002ddb7d8e715de7ea68288efbe4c42327c6df8107f18ddadf5  # [linux32]
  url: https://github.com/exercism/cli/releases/download/v{{ version }}/exercism-mac-64bit.tgz  # [osx]
  sha256: 6be784d6dd79ae04e47d5304b18cdc87d7be985b5bb1860a7dcd606259ce0efa  # [osx]
  url: https://github.com/exercism/cli/releases/download/v{{ version }}/exercism-windows-64bit.zip  # [win64]
  sha256: ce15ff4fd554ed49e4697372fc729ef2295757f150a272b24739dda70827a697  # [win64]
  url: https://github.com/exercism/cli/releases/download/v{{ version }}/exercism-windows-32bit.zip  # [win32]
  sha256: 0a0b6d8552b394b9018e7610fe68328ab5a6d5faabd65cbcc5a30b1854b7e3de  # [win32]

build:
  number: 0

requirements:
  build:
    - go

test:
  commands:
    - exercism --help

about:
  home: http://exercism.io
  license: MIT
  license_family: MIT
  summary: A Go based command line tool for exercism.io.

  description: |
    exercism.io is a platform for learning various programming languages by
    solving small exercises. This package provides the exercism command line
    client.
  doc_url: http://exercism.io/how-it-works/newbie
  dev_url: https://github.com/exercism/cli

extra:
  recipe-maintainers:
    - johanneskoester
