{% set name = "exercism" %}
{% set version = "3.0.3" %}

package:
  name: exercism
  version: {{ version }}

source:
  url: https://github.com/exercism/cli/releases/download/v{{ version }}/exercism-linux-64bit.tgz  # [linux64]
  sha256: 288eca36757a043f607f351c41ae7af5a37a1cc5ef68b104978dff8b47b02f5c  # [linux64]
  url: https://github.com/exercism/cli/releases/download/v{{ version }}/exercism-linux-32bit.tgz  # [linux32]
  sha256: f662680ab062707ce942075670474f464c026d26a074fdda4723996cf22826c2  # [linux32]
  url: https://github.com/exercism/cli/releases/download/v{{ version }}/exercism-mac-64bit.tgz  # [osx]
  sha256: d8bd8d37e282dd2b7b18682c9ac7b0c31f6e36aebf665fe4d611b8a36cb4e6d6  # [osx]
  url: https://github.com/exercism/cli/releases/download/v{{ version }}/exercism-windows-64bit.zip  # [win64]
  sha256: 3cdb373bcf791a3c36d502597c4b97a9f81588cad68523202f3bd7d6e023f93b  # [win64]
  url: https://github.com/exercism/cli/releases/download/v{{ version }}/exercism-windows-32bit.zip  # [win32]
  sha256: 66bf470b5eacdb43558e4ffcb2a7943055318d66a8b646fcdc6840ae476c9d10  # [win32]

build:
  number: 0

requirements:
  build:
    - go

test:
  commands:
    - exercism --help

about:
  home: http://exercism.io
  license: MIT
  license_family: MIT
  summary: A Go based command line tool for exercism.io.

  description: |
    exercism.io is a platform for learning various programming languages by
    solving small exercises. This package provides the exercism command line
    client.
  doc_url: http://exercism.io/how-it-works/newbie
  dev_url: https://github.com/exercism/cli

extra:
  recipe-maintainers:
    - johanneskoester
