{% set name = "exercism" %}
{% set version = "3.0.8" %}

package:
  name: exercism
  version: {{ version }}

source:
  url: https://github.com/exercism/cli/releases/download/v{{ version }}/exercism-linux-64bit.tgz  # [linux64]
  sha256: 0820c3abff965a1b472e5c3ad9113ed6ff6ce615b1b7442c3586574768b902b9  # [linux64]
  url: https://github.com/exercism/cli/releases/download/v{{ version }}/exercism-linux-32bit.tgz  # [linux32]
  sha256: 0315c4fa3c041b798c7dd29dfb605277b8a5e63f8aaeed261f4061b30d7ef2d6  # [linux32]
  url: https://github.com/exercism/cli/releases/download/v{{ version }}/exercism-mac-64bit.tgz  # [osx]
  sha256: bdba551420f85d64dc7407c95e13360dc25e70c776f7438297e017a8b4144d14  # [osx]
  url: https://github.com/exercism/cli/releases/download/v{{ version }}/exercism-windows-64bit.zip  # [win64]
  sha256: 65cc0f6bbbb29bf759d90a24e4dba2fd1fb9450aa605cb79287c949b90b5c5c2  # [win64]
  url: https://github.com/exercism/cli/releases/download/v{{ version }}/exercism-windows-32bit.zip  # [win32]
  sha256: 44fe2e810ad3a9d53e5cee3f7c9fa9eaa033187eb4dc78df3d48e6ac6dc32154  # [win32]

build:
  number: 0

requirements:
  build:
    - go

test:
  commands:
    - exercism --help

about:
  home: http://exercism.io
  license: MIT
  license_family: MIT
  summary: A Go based command line tool for exercism.io.

  description: |
    exercism.io is a platform for learning various programming languages by
    solving small exercises. This package provides the exercism command line
    client.
  doc_url: http://exercism.io/how-it-works/newbie
  dev_url: https://github.com/exercism/cli

extra:
  recipe-maintainers:
    - johanneskoester
